# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-pipelines

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: YarnInstaller@3
  inputs:
    versionSpec: 
    checkLatest: true
  displayName: 'Install Yarn'

- script: |
    yarn global add webpack webpack-cli nativescript
  displayName: 'Install Global packages'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"'
    noProfile: false
    noRc: false
  displayName: "Setup NativeScript"


- script: 'tns doctor'
  displayName: "Verify NativeScript Requirements"
  workingDirectory: ''



